Use C++ nullptr instead of NULL
This will be needed when we start using unique_ptr instead of deprecated
auto_ptr:

libs/acn/TCPTransport.cpp:319:7: error: call of overloaded 'unique_ptr(NULL)' is ambiguous
  319 |     : m_transport(NULL) {
      |       ^~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/14/memory:78,
                 from ./libs/acn/TCPTransport.h:34,
                 from libs/acn/TCPTransport.cpp:28:
/usr/include/c++/14/bits/unique_ptr.h:353:19: note: candidate: 'constexpr std::unique_ptr<_Tp, _Dp>::unique_ptr(std::nullptr_t) [with _Del = std::default_delete<ola::acn::IncomingStreamTransport>; <template-parameter-2-2> = void; _Tp = ola::acn::IncomingStreamTransport; _Dp = std::default_delete<ola::acn::IncomingStreamTransport>; std::nullptr_t = std::nullptr_t]'
  353 |         constexpr unique_ptr(nullptr_t) noexcept
      |                   ^~~~~~~~~~

This is only fixing up NULL usage where the compiler failed.