Handle RDMRequest consistently in DmxTriWidget.cpp
This will be needed when we start using unique_ptr instead of deprecated
auto_ptr:

plugins/usbpro/DmxTriWidget.cpp: In member function 'void ola::plugin::usbpro::DmxTriWidgetImpl::HandleRawRDMResponse(uint8_t, const uint8_t*, unsigned int)':
plugins/usbpro/DmxTriWidget.cpp:652:55: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = ola::rdm::RDMRequest; _Dp = std::default_delete<ola::rdm::RDMRequest>]'
  652 |   unique_ptr<RDMRequest> request(m_pending_rdm_request);
      |                                                       ^
In file included from /usr/include/c++/14/memory:78,
                 from plugins/usbpro/DmxTriWidget.cpp:23:
/usr/include/c++/14/bits/unique_ptr.h:516:7: note: declared here
  516 |       unique_ptr(const unique_ptr&) = delete;
      |       ^~~~~~~~~~